#ifndef __UVA_COMM_ENUM_H__
#define __UVA_COMM_ENUM_H__
enum {
  BLOCKING = 1000,
  NEWFACE_HANDLER = 100,
  MALLOC_HANDLER = 101,
  LOAD_HANDLER = 102,
  STORE_HANDLER = 103,
  STORE_HLRC_HANDLER = 104,
  SYNC_HANDLER = 105,
  MMAP_HANDLER = 106,
  MEMSET_HANDLER = 107,
  MEMCPY_HANDLER = 108,
  MEMCPY_HLRC_HANDLER = 109,
  GLOBAL_SEGFAULT_HANDLER = 110,
  HEAP_SEGFAULT_HANDLER = 111,
  GLOBAL_INIT_COMPLETE_HANDLER = 112
};
#endif
