#!/bin/bash
# Just kills a run if it goes on longer than an hour.

while [ 1 ]; do
  PROC=`ps -u autotest -o lstart,pid,cmd | grep 'mtcg.exe\|linked.exe\|opt' | sort -k 4 | head -1`
  if [ "$PROC" = "" ]; then
    sleep 10
    continue
  fi
  TIME=`echo $PROC | awk '{print $1 " " $2 " " $3 " " $4 " " $5}'`
  STARTTIME=`date -d "$TIME" +%s`
  CURTIME=`date +%s`
  DIFF=$(($CURTIME - $STARTTIME))
  HOURS=$(($DIFF / 3600))

  if [ "$HOURS" -ge "1" ]; then 
    PID=`echo $PROC | awk '{print $6}'`
    CMD=`echo $PROC | awk '{print $7}'`
    echo "watchdog trying to kill $PID $CMD"
    kill $PID
  fi
  sleep 10
done
